class AuthActions {
  static AUTH = {
    CHECK_PHONE: {
      REQUESTING: 'AUTH_CHECK_PHONE_REQUESTING',
      SUCCESS: 'AUTH_CHECK_PHONE_SUCCESS',
      ERROR: 'AUTH_CHECK_PHONE_ERROR',
      EMPTY: 'AUTH_CHECK_PHONE_EMPTY',
      SAVE_PHONE_NUMBER: `AUTH_SAVE_PHONE_NUMBER`,
    },
    CHECK_SMS_CODE: {
      REQUESTING: 'AUTH_CHECK_SMS_CODE_REQUESTING',
      SUCCESS: 'AUTH_CHECK_SMS_CODE_SUCCESS',
      ERROR: 'AUTH_CHECK_SMS_CODE_ERROR',
      SET_ACCESS_TOKEN: 'AUTH_SET_ACCESS_TOKEN',
      SET_USER_INFO: 'AUTH_SET_USER_INFO',
      REDIRECT_PATH: 'AUTH_CHECK_SMS_CODE_REDIRECT_PATH',
    },
    UPDATE_PROFILE: {
      REQUESTING: 'AUTH_UPDATE_PROFILE_REQUESTING',
      SUCCESS: 'AUTH_UPDATE_PROFILE_SUCCESS',
      ERROR: 'AUTH_UPDATE_PROFILE_ERROR',
    },
    CHANGE_FULLNAME_MODAL_STATUS: 'AUTH_CHANGE_FULLNAME_MODAL_STATUS',
    USER_INFO: {
      FILL: 'AUTH_USER_INFO_FILL',
      EMPTY: 'AUTH_USER_INFO_EMPTY',
    },
  };
}

export default AuthActions;
