class CargoActions {
  static CARGO = {
    CREATE: {
      REQUESTING: 'CARGO_CREATE_REQUESTING',
      SUCCESS: 'CARGO_CREATE_SUCCESS',
      ERROR: 'CARGO_CREATE_ERROR',
      FORM_SUBMIT_STATE: 'CARGO_CREATE_FORM_SUBMIT_STATE',
    },
    GET_CARGOES: {
      REQUESTING: 'CARGO_GET_CARGOES_REQUESTING',
      SUCCESS: 'CARGO_GET_CARGOES_SUCCESS',
      ERROR: 'CARGO_GET_CARGOES_ERROR',
    },
  };
}

export default CargoActions;
