class NotificationActions {
  static NOTIFICATION = {
    ERROR: {
      SET_ERROR_RESPONSE: 'NOTIFICATION_ERROR_SET_ERROR_RESPONSE',
      EMPTY_ERROR_RESPONSE: 'NOTIFICATION_ERROR_EMPTY_ERROR_RESPONSE',
    },
    SUCCESS: {
      SET_SUCCESS_RESPONSE: 'NOTIFICATION_SUCCESS_SET_SUCCESS_RESPONSE',
      EMPTY_SUCCESS_RESPONSE: 'NOTIFICATION_SUCCESS_EMPTY_SUCCESS_RESPONSE',
    },
  };
}

export default NotificationActions;
