const ActionTypes = {
  AUTH: {
    REFRESH_TOKEN: {
      REQUESTING: 'REFRESH_TOKEN_REQUESTING',
      SUCCESS: 'REFRESH_TOKEN_SUCCESS',
      ERROR: 'REFRESH_TOKEN_ERROR',
      SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
      SET_USER_INFO: 'SET_USER_INFO',
    },
    CHECK_PHONE: {
      REQUESTING: 'CHECK_PHONE_REQUESTING',
      SUCCESS: 'CHECK_PHONE_SUCCESS',
      ERROR: 'CHECK_PHONE_ERROR',
      EMPTY: 'CHECK_PHONE_EMPTY',
      SAVE_PHONE_NUMBER: `SAVE_PHONE_NUMBER`,
    },
    SAVE_USER_TOKEN_AND_PHONE: 'SAVE_USER_TOKEN_AND_PHONE',
    CHECK_SMS_CODE: {
      REQUESTING: 'CHECK_SMS_CODE_REQUESTING',
      SUCCESS: 'CHECK_SMS_CODE_SUCCESS',
      ERROR: 'CHECK_SMS_CODE_ERROR',
      EMPTY: 'CHECK_SMS_CODE_EMPTY',
    },
    LOGIN: {
      REQUESTING: 'LOGIN_REQUESTING',
      SUCCESS: 'LOGIN_SUCCESS',
      ERROR: 'LOGIN_ERROR',
      SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
      SET_USER_INFO: 'SET_USER_INFO',
      REDIRECT_PATH: 'LOGIN_REDIRECT_PATH',
    },
    REGISTER: {
      REQUESTING: 'REGISTER_REQUESTING',
      SUCCESS: 'REGISTER_SUCCESS',
      ERROR: 'REGISTER_ERROR',
      SET_ERROR_MESSAGES: 'SET_ERROR_MESSAGES',
      RESET: 'REGISTER_RESET',
    },
    RESET_PASSWORD: {
      REQUESTING: 'RESET_PASSWORD_REQUESTING',
      SUCCESS: 'RESET_PASSWORD_SUCCESS',
      ERROR: 'RESET_PASSWORD_ERROR',
    },
    LOGOUT: 'LOGOUT',
    AUTH_MODAL_STATUS: 'AUTH_MODAL_STATUS',
    CHECK_ACCESS_TOKEN: 'AUTH_CHECK_ACCESS_TOKEN',
    SET_EXPIRES_IN: 'AUTH_ACCESS_TOKEN_SET_EXPIRES_IN',
  },
  MENUS: {
    GET_ALL: 'MENUS_GET_ALL',
    ALL_MENUS: {
      REQUESTING: 'ALL_MENUS_REQUESTING',
      SUCCESS: 'ALL_MENUS_SUCCESS',
    },
    FOOTER: {
      REQUESTING: 'MENUS_FOOTER_REQUESTING',
      SUCCESS: 'MENUS_FOOTER_SUCCESS',
    },
    HEADER: {
      REQUESTING: 'MENUS_HEADER_REQUESTING',
      SUCCESS: 'MENUS_HEADER_SUCCESS',
    },
    CATEGORY: {
      REQUESTING: 'MENUS_CATEGORY_REQUESTING',
      SUCCESS: 'MENUS_CATEGORY_SUCCESS',
    },
    SUBSCRIPTION: {
      REQUESTING: 'MENUS_SUBSCRIPTION_REQUESTING',
      SUCCESS: 'MENUS_SUBSCRIPTION_SUCCESS',
    },
    MINIMAL: {
      REQUESTING: 'MENUS_MINIMAL_REQUESTING',
      SUCCESS: 'MENUS_MINIMAL_SUCCESS',
    },
  },
  BASE_INFO: {
    CATEGORIES: {
      REQUESTING: 'BASE_INFO_CATEGORIES_REQUESTING',
      SUCCESS: 'BASE_INFO_CATEGORIES_SUCCESS',
    },
    BANKS: {
      REQUESTING: 'BASE_INFO_BANKS_REQUESTING',
      SUCCESS: 'BASE_INFO_BANKS_SUCCESS',
    },
    COUNTRIES: {
      REQUESTING: 'BASE_INFO_COUNTRIES_REQUESTING',
      SUCCESS: 'BASE_INFO_COUNTRIES_SUCCESS',
    },
    PROVINCES: {
      REQUESTING: 'BASE_INFO_PROVINCES_REQUESTING',
      SUCCESS: 'BASE_INFO_PROVINCES_SUCCESS',
    },
    CITIES: {
      REQUESTING: 'BASE_INFO_CITIES_REQUESTING',
      SUCCESS: 'BASE_INFO_CITIES_SUCCESS',
    },
    SETTINGS: {
      REQUESTING: 'BASE_INFO_SETTINGS_REQUESTING',
      SUCCESS: 'BASE_INFO_SETTINGS_SUCCESS',
    },
  },
  PRODUCTS: {
    CATALOG: {
      CLEARING: 'CATALOG_CLEARING',
      REQUESTING: 'CATALOG_REQUESTING',
      SUCCESS: 'CATALOG_SUCCESS',
      ERROR: 'CATALOG_ERROR',
      CHEAPEST_VARIATION: 'CHEAPEST_VARIATION',
    },
    COMPARE: 'PRODUCTS_COMPARE',
    COMPARE_PRODUCTS: {
      REQUESTING: 'PRODUCTS_COMPARE_PRODUCTS_REQUESTING',
      SUCCESS: 'PRODUCTS_COMPARE_PRODUCTS_SUCCESS',
      ERROR: 'PRODUCTS_COMPARE_PRODUCTS_ERROR',
    },
    COMMENTS: {
      REQUESTING: 'COMMENTS_REQUESTING',
      SUCCESS: 'COMMENTS_SUCCESS',
      ERROR: 'COMMENTS_ERROR',
    },
    SUBMIT_COMMENT: {
      REQUESTING: 'SUBMIT_COMMENT_REQUESTING',
      SUCCESS: 'SUBMIT_COMMENT_SUCCESS',
      ERROR: 'SUBMIT_COMMENT_ERROR',
    },
    VOTE: {
      REQUESTING: 'VOTE_REQUESTING',
      SUCCESS: 'VOTE_SUCCESS',
      ERROR: 'VOTE_ERROR',
    },
    UNVOTE: {
      REQUESTING: 'UNVOTE_REQUESTING',
      SUCCESS: 'UNVOTE_SUCCESS',
      ERROR: 'UNVOTE_ERROR',
    },
    QUESTIONS: {
      REQUESTING: 'QUESTIONS_REQUESTING',
      SUCCESS: 'QUESTIONS_SUCCESS',
      ERROR: 'QUESTIONS_ERROR',
    },
    SUBMIT_QUESTION: {
      REQUESTING: 'SUBMIT_QUESTION_REQUESTING',
      SUCCESS: 'SUBMIT_QUESTION_SUCCESS',
      ERROR: 'SUBMIT_QUESTION_ERROR',
    },
    RESPOND_TO_QUESTION: {
      REQUESTING: 'RESPOND_TO_QUESTION_REQUESTING',
      SUCCESS: 'RESPOND_TO_QUESTION_SUCCESS',
      ERROR: 'RESPOND_TO_QUESTION_ERROR',
    },
    ADD_TO_WISH_LIST: {
      REQUESTING: 'ADD_TO_WISH_LIST_REQUESTING',
      SUCCESS: 'ADD_TO_WISH_LIST_SUCCESS',
      ERROR: 'ADD_TO_WISH_LIST_ERROR',
    },
    REMOVE_WISH_LIST: {
      REQUESTING: 'REMOVE_WISH_LIST_REQUESTING',
      SUCCESS: 'REMOVE_WISH_LIST_SUCCESS',
      ERROR: 'REMOVE_WISH_LIST_ERROR',
    },
    IS_WISHED: 'PRODUCTS_IS_WISHED',
    WISH_LIST_TOOLTIP: 'WISH_LIST_TOOLTIP',
    INFORM_ME: {
      REQUESTING: 'PRODUCTS_INFORM_ME_REQUESTING',
      SUCCESS: 'PRODUCTS_INFORM_ME_SUCCESS',
      ERROR: 'PRODUCTS_INFORM_ME_ERROR',
    },
    REMOVE_INFORM_ME: {
      REQUESTING: 'PRODUCTS_REMOVE_INFORM_ME_REQUESTING',
      SUCCESS: 'PRODUCTS_REMOVE_INFORM_ME_SUCCESS',
      ERROR: 'PRODUCTS_REMOVE_INFORM_ME_ERROR',
    },
    IS_INFORMED: 'PRODUCTS_IS_INFORMED',
    OTHER_SUPPLIERS: {
      REQUESTING: 'OTHER_SUPPLIERS_REQUESTING',
      SUCCESS: 'OTHER_SUPPLIERS_SUCCESS',
      ERROR: 'OTHER_SUPPLIERS_ERROR',
    },
    SIMILAR: {
      REQUESTING: 'PRODUCTS_SIMILAR_REQUESTING',
      SUCCESS: 'PRODUCTS_SIMILAR_SUCCESS',
      ERROR: 'PRODUCTS_SIMILAR_ERROR',
    },
    ON_SALE: {
      REQUESTING: 'PRODUCTS_ON_SALE_REQUESTING',
      SUCCESS: 'PRODUCTS_ON_SALE_SUCCESS',
      ERROR: 'PRODUCTS_ON_SALE_ERROR',
    },
    EXPRESS: {
      REQUESTING: 'PRODUCTS_EXPRESS_REQUESTING',
      SUCCESS: 'PRODUCTS_EXPRESS_SUCCESS',
      ERROR: 'PRODUCTS_EXPRESS_ERROR',
    },
    CHINA: {
      REQUESTING: 'PRODUCTS_CHINA_REQUESTING',
      SUCCESS: 'PRODUCTS_CHINA_SUCCESS',
      ERROR: 'PRODUCTS_CHINA_ERROR',
    },
    TURKEY: {
      REQUESTING: 'PRODUCTS_TURKEY_REQUESTING',
      SUCCESS: 'PRODUCTS_TURKEY_SUCCESS',
      ERROR: 'PRODUCTS_TURKEY_ERROR',
    },
    EMARAT: {
      REQUESTING: 'PRODUCTS_EMARAT_REQUESTING',
      SUCCESS: 'PRODUCTS_EMARAT_SUCCESS',
      ERROR: 'PRODUCTS_EMARAT_ERROR',
    },
    PELAZIO: {
      REQUESTING: 'PRODUCTS_PELAZIO_REQUESTING',
      SUCCESS: 'PRODUCTS_PELAZIO_SUCCESS',
      ERROR: 'PRODUCTS_PELAZIO_ERROR',
    },
    LAST_SEEN: {
      REQUESTING: 'PRODUCTS_LAST_SEEN_REQUESTING',
      SUCCESS: 'PRODUCTS_LAST_SEEN_SUCCESS',
      ERROR: 'PRODUCTS_LAST_SEEN_ERROR',
    },
    MOBILE: {
      REQUESTING: 'PRODUCTS_MOBILE_REQUESTING',
      SUCCESS: 'PRODUCTS_MOBILE_SUCCESS',
      ERROR: 'PRODUCTS_MOBILE_ERROR',
    },
    PRICE_HISTORY: {
      REQUESTING: 'PRODUCTS_PRICE_HISTORY_REQUESTING',
      SUCCESS: 'PRODUCTS_PRICE_HISTORY_SUCCESS',
      ERROR: 'PRODUCTS_PRICE_HISTORY_ERROR',
    },
  },
  BANNERS: {
    HOMEPAGE: {
      ALL_BANNERS: {
        REQUESTING: 'ALL_BANNERS_REQUESTING',
        SUCCESS: 'ALL_BANNERS_SUCCESS',
        ERROR: 'ALL_BANNERS_ERROR',
      },
      BANNER_A: {
        REQUESTING: 'BANNER_A_REQUESTING',
        SUCCESS: 'BANNER_A_SUCCESS',
        ERROR: 'BANNER_A_ERROR',
      },
      BANNER_B: {
        REQUESTING: 'BANNER_B_REQUESTING',
        SUCCESS: 'BANNER_B_SUCCESS',
        ERROR: 'BANNER_B_ERROR',
      },
      BANNER_C: {
        REQUESTING: 'BANNER_C_REQUESTING',
        SUCCESS: 'BANNER_C_SUCCESS',
        ERROR: 'BANNER_C_ERROR',
      },
      BANNER_D: {
        REQUESTING: 'BANNER_D_REQUESTING',
        SUCCESS: 'BANNER_D_SUCCESS',
        ERROR: 'BANNER_D_ERROR',
      },
      BANNER_E: {
        REQUESTING: 'BANNER_E_REQUESTING',
        SUCCESS: 'BANNER_E_SUCCESS',
        ERROR: 'BANNER_E_ERROR',
      },
      SLIDE_SHOW: {
        REQUESTING: 'BANNERS_SLIDER_REQUESTING',
        SUCCESS: 'SLIDE_SHOW_SUCCESS',
        ERROR: 'SLIDE_SHOW_ERROR',
      },
    },
  },
  CART: {
    SET_CART_INFO: 'SET_CART_INFO',
    SET_CREDIT_INFO: 'SET_CREDIT_INFO',
    ADD: {
      INIT: 'ADD_CART_INIT',
      REQUESTING: 'ADD_CART_REQUESTING',
      SUCCESS: 'ADD_CART_SUCCESS',
      ERROR: 'ADD_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    UPDATE: {
      INIT: 'UPDATE_CART_INIT',
      REQUESTING: 'UPDATE_CART_REQUESTING',
      SUCCESS: 'UPDATE_CART_SUCCESS',
      ERROR: 'UPDATE_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    REFRESH: {
      REQUESTING: 'REFRESH_CART_REQUESTING',
      SUCCESS: 'REFRESH_CART_SUCCESS',
      ERROR: 'REFRESH_CART_ERROR',
    },
    SHOW: {
      REQUESTING: 'SHOW_CART_REQUESTING',
      SUCCESS: 'SHOW_CART_SUCCESS',
      ERROR: 'SHOW_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    INCREASE: {
      REQUESTING: 'INCREASE_CART_REQUESTING',
      SUCCESS: 'INCREASE_CART_SUCCESS',
      ERROR: 'INCREASE_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    DECREASE: {
      REQUESTING: 'DECREASE_CART_REQUESTING',
      SUCCESS: 'DECREASE_CART_SUCCESS',
      ERROR: 'DECREASE_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    DESTROY: {
      REQUESTING: 'DESTROY_CART_REQUESTING',
      SUCCESS: 'DESTROY_CART_SUCCESS',
      ERROR: 'DESTROY_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    DESTROY_ITEM: {
      REQUESTING: 'DESTROY_ITEM_CART_REQUESTING',
      SUCCESS: 'DESTROY_ITEM_CART_SUCCESS',
      ERROR: 'DESTROY_ITEM_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    APPLY_VOUCHER_GIFT: {
      INIT: 'APPLY_VOUCHER_GIFT_CART_INIT',
      REQUESTING: 'APPLY_VOUCHER_GIFT_CART_REQUESTING',
      SUCCESS: 'APPLY_VOUCHER_GIFT_CART_SUCCESS',
      ERROR: 'APPLY_VOUCHER_GIFT_CART_ERROR',
    },
    APPLY_VOUCHER: {
      INIT: 'APPLY_VOUCHER_CART_INIT',
      REQUESTING: 'APPLY_VOUCHER_CART_REQUESTING',
      SUCCESS: 'APPLY_VOUCHER_CART_SUCCESS',
      ERROR: 'APPLY_VOUCHER_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    REMOVE_VOUCHER: {
      INIT: 'REMOVE_VOUCHER_CART_INIT',
      REQUESTING: 'REMOVE_VOUCHER_CART_REQUESTING',
      SUCCESS: 'REMOVE_VOUCHER_CART_SUCCESS',
      ERROR: 'REMOVE_VOUCHER_CART_ERROR',
      SET_CART_INFO: 'SET_CART_INFO',
    },
    MOVE_TO_SHOP: {
      REQUESTING: 'MOVE_TO_SHOP_LIST_REQUESTING',
      SUCCESS: 'MOVE_TO_SHOP_LIST_SUCCESS',
      ERROR: 'MOVE_TO_SHOP_LIST_ERROR',
      SET_SHOP_LIST_INFO: 'SET_SHOP_LIST_INFO',
    },
  },
  SHOP_LIST: {
    SET_SHOP_LIST_INFO: 'SET_SHOP_LIST_INFO',
    REMOVE_ITEM_FROM_SHOP_LIST: 'REMOVE_ITEM_FROM_SHOP_LIST',
    ADD_ITEM_TO_SHOP_LIST: 'ADD_ITEM_TO_SHOP_LIST',
    SET_SHOP_ITEM_INFO: 'SET_SHOP_ITEM_INFO',
    SHOW: {
      REQUESTING: 'SHOW_SHOP_LIST_REQUESTING',
      SUCCESS: 'SHOW_SHOP_LIST_SUCCESS',
      ERROR: 'SHOW_SHOP_LIST_ERROR',
      SET_SHOP_LIST_INFO: 'SET_SHOP_LIST_INFO',
    },

    MOVE_TO_CART: {
      REQUESTING: 'MOVE_TO_CART_REQUESTING',
      SUCCESS: 'MOVE_TO_CART_SUCCESS',
      ERROR: 'MOVE_TO_CART_ERROR',
      SET_SHOP_LIST_INFO: 'SET_SHOP_LIST_INFO',
    },
    ADD: {
      INIT: 'Add_TO_SHOP_LIST_INIT',
      REQUESTING: 'Add_TO_SHOP_LIST_REQUESTING',
      SUCCESS: 'Add_TO_SHOP_LIST_SUCCESS',
      ERROR: 'Add_TO_SHOP_LIST_ERROR',
      SET_SHOP_LIST_INFO: 'SET_SHOP_LIST_INFO',
    },
    DESTROY_ITEM: {
      REQUESTING: 'DESTROY_ITEM_SHOP_LIST_REQUESTING',
      SUCCESS: 'DESTROY_ITEM_SHOP_LIST_SUCCESS',
      ERROR: 'DESTROY_ITEM_SHOP_LIST_ERROR',
      SET_SHOP_LIST_INFO: 'SET_SHOP_LIST_INFO',
    },
  },
  ADDRESS: {
    SET_ADDRESS_LIST: 'SET_ADDRESS_LIST',
    ADD_OR_EDIT_ADDRESS_STATUS: 'ADD_OR_EDIT_ADDRESS_STATUS',
    ADD: {
      INIT: 'ADD_ADDRESS_INIT',
      REQUESTING: 'ADD_ADDRESS_REQUESTING',
      SUCCESS: 'ADD_ADDRESS_SUCCESS',
      ERROR: 'ADD_ADDRESS_ERROR',
    },
    UPDATE: {
      INIT: 'UPDATE_ADDRESS_INIT',
      REQUESTING: 'UPDATE_ADDRESS_REQUESTING',
      SUCCESS: 'UPDATE_ADDRESS_SUCCESS',
      ERROR: 'UPDATE_ADDRESS_ERROR',
    },
    DELETE: {
      REQUESTING: 'DELETE_ADDRESS_REQUESTING',
      SUCCESS: 'DELETE_ADDRESS_SUCCESS',
      ERROR: 'DELETE_ADDRESS_ERROR',
      RESET_NEW_ADDRESS: 'RESET_NEW_ADDRESS',
    },
    SHOW: {
      REQUESTING: 'SHOW_ADDRESS_REQUESTING',
      SUCCESS: 'SHOW_ADDRESS_SUCCESS',
      ERROR: 'SHOW_ADDRESS_ERROR',
    },
  },
  DELIVERIES: {
    GET_DELIVERIES: {
      REQUESTING: 'GET_DELIVERIES_REQUESTING',
      SUCCESS: 'GET_DELIVERIES_SUCCESS',
      ERROR: 'GET_DELIVERIES_ERROR',
    },
    SET_DELIVERIES: 'SET_DELIVERIES',
  },

  CONTACT_US: {
    REQUESTING: 'CONTACT_US_REQUESTING',
    SUCCESS: 'CONTACT_US_SUCCESS',
    ERROR: 'CONTACT_US_ERROR',
    RESET_FORM: 'CONTACT_US_RESET_FORM',
    GET_TYPES: {
      REQUESTING: 'GET_TYPES_REQUESTING',
      SUCCESS: 'GET_TYPES_SUCCESS',
      ERROR: 'GET_TYPES_ERROR',
    },
  },
  SEARCH: {
    REQUESTING: 'SEARCH_REQUESTING',
    SUCCESS: 'SEARCH_SUCCESS',
    ERROR: 'SEARCH_ERROR',
    UPDATE_QUERY: 'SEARCH_UPDATE_QUERY',
  },
  SUPPLIER_INFO: {
    REQUESTING: 'SUPPLIER_INFO_REQUESTING',
    SUCCESS: 'SUPPLIER_INFO_SUCCESS',
    ERROR: 'SUPPLIER_INFO_ERROR',
  },
  AUTO_COMPLETE_SEARCH: {
    REQUESTING: 'AUTO_COMPLETE_SEARCH_REQUESTING',
    SUCCESS: 'AUTO_COMPLETE_SEARCH_SUCCESS',
    ERROR: 'AUTO_COMPLETE_SEARCH_ERROR',
    EMPTY: 'AUTO_COMPLETE_SEARCH_EMPTY',
  },
  REQUEST: {
    GET_ALL: {
      REQUESTING: 'REQUEST_GET_ALL_REQUESTING',
      SUCCESS: 'REQUEST_GET_ALL_SUCCESS',
      ERROR: 'REQUEST_GET_ALL_ERROR',
    },
    SHOW_SINGLE: {
      REQUESTING: 'REQUEST_SHOW_SINGLE_REQUESTING',
      SUCCESS: 'REQUEST_SHOW_SINGLE_SUCCESS',
      ERROR: 'REQUEST_SHOW_SINGLE_ERROR',
    },
    CREATE: {
      REQUESTING: 'REQUEST_CREATE_REQUESTING',
      SUCCESS: 'REQUEST_CREATE_SUCCESS',
      ERROR: 'REQUEST_CREATE_ERROR',
      IS_MODAL_OPEN: 'IS_MODAL_OPEN',
    },
  },
  ORDER: {
    ORDERS: {
      REQUESTING: 'ORDERS_REQUESTING',
      SUCCESS: 'ORDERS_SUCCESS',
      ERROR: 'ORDERS_ERROR',
    },
    SINGLE_ORDER: {
      REQUESTING: 'SINGLE_ORDER_REQUESTING',
      SUCCESS: 'SINGLE_ORDER_SUCCESS',
      ERROR: 'SINGLE_ORDER_ERROR',
    },
    SET_ORDER_INFO: 'SET_ORDER_INFO',
    CREATE: {
      INIT: 'CREATE_ORDER_INIT',
      REQUESTING: 'CREATE_ORDER_REQUESTING',
      SUCCESS: 'CREATE_ORDER_SUCCESS',
      ERROR: 'CREATE_ORDER_ERROR',
    },
    RETRY: {
      INIT: 'RETRY_ORDER_INIT',
      REQUESTING: 'RETRY_ORDER_REQUESTING',
      SUCCESS: 'RETRY_ORDER_SUCCESS',
      ERROR: 'RETRY_ORDER_ERROR',
    },
  },
  PAYMENT: {
    CHECK: {
      INIT: 'CHECK_PAYMENT_INIT',
      REQUESTING: 'CHECK_PAYMENT_REQUESTING',
      SUCCESS: 'CHECK_PAYMENT_SUCCESS',
      ERROR: 'CHECK_PAYMENT_ERROR',
    },
  },
  NOTIFICATION: {
    ERROR: {
      SET_ERROR_RESPONSE: 'SET_ERROR_RESPONSE',
      EMPTY_ERROR_RESPONSE: 'EMPTY_ERROR_RESPONSE',
    },
    SUCCESS: {
      SET_SUCCESS_RESPONSE: 'SET_SUCCESS_RESPONSE',
      EMPTY_SUCCESS_RESPONSE: 'EMPTY_SUCCESS_RESPONSE',
    },
  },
  PROFILE: {
    SET_PROFILE_INFO: 'SET_PROFILE_INFO',
    SHOW: {
      REQUESTING: 'SHOW_PROFILE_REQUESTING',
      SUCCESS: 'SHOW_PROFILE_SUCCESS',
      ERROR: 'SHOW_PROFILE_ERROR',
    },
    BALANCE: {
      REQUESTING: 'BALANCE_PROFILE_REQUESTING',
      SUCCESS: 'BALANCE_PROFILE_SUCCESS',
      ERROR: 'BALANCE_PROFILE_ERROR',
    },
    UPDATE: {
      INIT: 'UPDATE_PROFILE_INIT',
      REQUESTING: 'UPDATE_PROFILE_REQUESTING',
      SUCCESS: 'UPDATE_PROFILE_SUCCESS',
      ERROR: 'UPDATE_PROFILE_ERROR',
    },
    UPDATE_NATIONAL_CODE: {
      REQUESTING: 'UPDATE_NATIONAL_CODE_REQUESTING',
      SUCCESS: 'UPDATE_NATIONAL_CODE_SUCCESS',
      ERROR: 'UPDATE_NATIONAL_CODE_ERROR',
      MODAL_STATUS: 'UPDATE_NATIONAL_CODE_MODAL_STATUS',
    },
    UPDATE_PHOTO: {
      INIT: 'UPDATE_PROFILE_PHOTO_INIT',
      REQUESTING: 'UPDATE_PROFILE_PHOTO_REQUESTING',
      SUCCESS: 'UPDATE_PROFILE_PHOTO_SUCCESS',
      ERROR: 'UPDATE_PROFILE_PHOTO_ERROR',
    },
    CHANGE_PASSWORD: {
      INIT: 'CHANGE_PASSWORD_INIT',
      REQUESTING: 'CHANGE_PASSWORD_REQUESTING',
      SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
      ERROR: 'CHANGE_PASSWORD_ERROR',
    },
    GET_WISHLIST: {
      REQUESTING: 'GET_WISHLIST_REQUESTING',
      SUCCESS: 'GET_WISHLIST_SUCCESS',
      ERROR: 'GET_WISHLIST_ERROR',
    },
  },
  ERRORS: {
    HAPPENED: 'ACTION_TYPES_ERROR_HAPPENED',
  },
};

export default ActionTypes;
